# Generated by Django 2.0.2 on 2018-06-01 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotationtools', '0003_auto_20180601_1223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectdatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ID', models.CharField(max_length=100)),
                ('annotation_state', models.IntegerField(choices=[(0, 'NotAnnotated'), (1, 'BeingAnnotated'), (2, 'Annotated')], default=0)),
                ('annotated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationtools.Datasets')),
            ],
        ),
    ]
