# Generated by Django 2.0.2 on 2018-04-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotated_videos',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('annotated', models.BooleanField(default=False)),
                ('validation', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_name', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
