# Generated by Django 2.0.2 on 2018-04-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoannotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=100)),
                ('validation', models.BooleanField(default=False)),
                ('watched', models.BooleanField(default=False)),
            ],
        ),
    ]
