# Generated by Django 2.0.2 on 2018-04-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoannotation', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Annotators',
        ),
    ]
