# Generated by Django 2.0.2 on 2018-04-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoannotation', '0004_annotators_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotators',
            name='validation',
        ),
        migrations.RemoveField(
            model_name='annotators',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='annotators',
            name='watched',
        ),
    ]
