# Generated by Django 2.0.2 on 2018-04-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoannotation', '0006_auto_20180418_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation_details',
            old_name='video_id',
            new_name='video',
        ),
    ]
