# Generated by Django 2.0.2 on 2018-05-22 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(choices=[(0, 'Skip'), (1, 'Yes'), (2, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ID', models.CharField(max_length=100)),
                ('yes_count', models.IntegerField(default=0)),
                ('no_count', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('dataset_type', models.IntegerField(choices=[(0, 'VideoAnnotation'), (1, 'ImageAnnotation')])),
                ('dataset_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ID', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationtools.Datasets')),
            ],
        ),
        migrations.CreateModel(
            name='User_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_data_id', models.CharField(default='', max_length=100)),
                ('skip_count', models.IntegerField(default=0)),
                ('yes_count', models.IntegerField(default=0)),
                ('no_count', models.IntegerField(default=0)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationtools.Labels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationtools.Labels'),
        ),
        migrations.AddField(
            model_name='annotation_history',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationtools.Data'),
        ),
        migrations.AddField(
            model_name='annotation_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='user_state',
            unique_together={('user', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='labels',
            unique_together={('dataset', 'label_ID')},
        ),
        migrations.AlterUniqueTogether(
            name='annotation_history',
            unique_together={('user', 'data')},
        ),
    ]
