# Generated by Django 2.0.2 on 2018-05-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationtools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasets',
            name='dataset_type',
            field=models.IntegerField(choices=[(0, 'VideoAnnotation'), (1, 'ImageAnnotation'), (2, 'ObjectRecognition')]),
        ),
    ]
